steps:
  - label: ":package: Build images"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - wait: ~
    continue_on_failure: false

  - label: "Run unit test"
    command: echo "Run test!"

  - label: "Run functional test"
    command: echo "Run functional test!"

  - wait: ~
    continue_on_failure: false

  - block: ":shipit: Release to dev"
    branches: "master"
    

  - label: "Deploying to dev"
    command: echo "Deploying to dev!"

  - wait

  - block: ":shipit: Release to stg"
    branches: "master"

  - label: "Deploying to stg"
    command: echo "Deploying to stg!"

  - block: ":shipit: Release to canary"
    branches: "pay2release"

  - input: "Release ticket"
    branches: "pay2release"
    fields:
      - text: "Jira ticket"
        key: "jira-ticket"

  - label: "Deploying to canary"
    branches: "pay2release"
    command: echo "Deploying to canary!"

  - wait: ~
    branches: "pay2release"
    continue_on_failure: false

  - label: "Run Integration test"
    branches: "pay2release"
    command: echo "Run test!"

  - label: "Bake time in Canary"
    branches: "pay2release"
    command: sleep 1m

  - wait
    branches: "pay2release"

  - label: "Check the metric"
    branches: "pay2release"
    command: echo "Check metric"

  - block: ":shipit: Release to Prod"
    branches: "pay2release"
    branches: "pay2release"

  - input: "Release ticket"
    branches: "pay2release"
    fields:
      - text: "Jira ticket"
        key: "jira-ticket"

  - label: "Deploying to Prod"
    branches: "pay2release"
    command: echo "Deploying to prod!"

  - label: "Bake time in Prod"
    branches: "pay2release"
    command: sleep 1m

  - wait
    branches: "pay2release"

  - label: "Check the metric"
    branches: "pay2release"
    command: echo "Check metric"