steps:
  - label: ":package: Build images"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - wait: ~
    continue_on_failure: false

  - label: ":partyparrot: Run unit test"
    command: echo "Run test!"

  - label: ":partyparrot: Run functional test"
    command: echo "Run functional test!"

  - wait: ~
    continue_on_failure: false

  - block: ":rocket: Release to dev"
    branches: "master"
    

  - label: ":argocd:  Deploying to dev"
    command: echo "Deploying to dev!"

  - wait

  - block: ":rocket: Release to stg"
    branches: "master"

  - label: ":argocd: Deploying to stg"
    command: echo "Deploying to stg!"

  - block: ":rocket: Release to canary"
    if: build.tag =~ /^v\//

  - input: ":jira: Release ticket"
    if: build.tag =~ /^v\//
    fields:
      - text: "Jira ticket"
        key: "jira-ticket"

  - label: ":argocd: Deploying to canary"
    if: build.tag =~ /^v\//
    command: echo "Deploying to canary!"

  - wait: ~
    continue_on_failure: false

  - label: ":partyparrot: Run Integration test"
    if: build.tag =~ /^v\//
    command: echo "Run test!"

  - label: ":alarm_clock: Bake time in Canary"
    if: build.tag =~ /^v\//
    command: sleep 1m

  - wait

  - label: ":newrelic: Check the metric"
    if: build.tag =~ /^v\//
    command: echo "Check metric"

  - block: ":rocket: Release to Prod"
    if: build.tag =~ /^v\//

  - input: ":jira: Release ticket"
    if: build.tag =~ /^v\//
    fields:
      - text: "Jira ticket"
        key: "jira-ticket"

  - label: ":argocd: Deploying to Prod"
    if: build.tag =~ /^v\//
    command: echo "Deploying to prod!"

  - label: ":alarm_clock: Bake time in Prod"
    if: build.tag =~ /^v\//
    command: sleep 1m

  - wait

  - label: ":newrelic: Check the metric"
    if: build.tag =~ /^v\//
    command: echo "Check metric"

  - block: ":fire_extinguisher: Trigger prod rollback"
    if: build.tag =~ /^v\//

  - label: ":skull_and_crossbones: Prod rollback"
    if: build.tag =~ /^v\//
    command: echo "Prod rollback!"